[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/F5gsff5z--PUD-jYszM8ErWKLSmCnmhh", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/F5gsff5z--PUD-jYszM8ErWKLSmCnmhh" }
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@chainlink-local/=lib/chainlink-local/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
